# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
include: 'https://gitlab.com/avron/avron.gitlab.io/-/raw/master/debian-test.yml'


variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo
  except:
    - master

pages:
  image: registry.gitlab.com/pages/hugo:latest
  script:
    - hugo new site test && cd test
    - mkdir themes/gruvhugo 
    - cp -r ../archetypes themes/gruvhugo
    - cp -r ../exampleSite themes/gruvhugo 
    - cp -r ../layouts themes/gruvhugo
    - cp ../LICENSE themes/gruvhugo
    - cp ../README.md themes/gruvhugo
    - cp -r ../static themes/gruvhugo
    - cp ../theme.toml themes/gruvhugo
    - rm -rf ../content && cp -r themes/gruvhugo/exampleSite/content/ . 
    - rm config.toml && cp themes/gruvhugo/exampleSite/deploy.toml ./config.toml 
    - hugo
    - mv public ../
  artifacts:
    paths:
      - public
  only:
    - master
