variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  image: "debian:unstable"
  script:
    - rm -rf public
    - cat /etc/*release
    - apt install wget
    - wget https://github.com/gohugoio/hugo/releases/download/v0.85.0/hugo_0.85.0_Linux-64bit.deb
    - dpkg -i *.deb
    - hugo env
    - hugo new site test && cd test
    - mkdir themes/gruvhugo 
    - cp -r ../archetypes themes/gruvhugo
    - cp -r ../exampleSite themes/gruvhugo 
    - cp -r ../layouts themes/gruvhugo
    - cp ../LICENSE.md themes/gruvhugo
    - cp ../README.md themes/gruvhugo
    - cp -r ../static themes/gruvhugo
    - cp ../theme.toml themes/gruvhugo
    - rm -rf ../content && cp -r themes/gruvhugo/exampleSite/content/ . 
    - rm config.toml && cp themes/gruvhugo/exampleSite/deploy.toml ./config.toml 
    - mkdir static/img && cp themes/gruvhugo/static/img/logo.png static/img
    - hugo
    - mv public ../
  artifacts:
    paths:
      - public
  only:
    - master
