image: "debian:stable"

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update -y
  - apt-get install -y hugo
  - hugo new site test && cd test
  - git submodule add https://gitlab.com/avron/gruvhugo themes/gruvhugo
  - rm -rf content && cp -r themes/gruvhugo/exampleSite/content/ . 
  - rm config.toml && cp themes/gruvhugo/exampleSite/config.toml . 
  - ls -a

serve:
  stage: deploy
  script:
  - hugo
  - cd ..
  artifacts:
    paths:
    - test
  only:
  - master
