variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

build-branch:
  stage: build
  image: "debian:stable"
  script:
  - apt-get update -y
  - apt-get install -y hugo git
  - hugo new site test && cd test
  - git submodule add https://gitlab.com/avron/gruvhugo themes/gruvhugo
  - rm -rf content && cp -r themes/gruvhugo/exampleSite/content/ . 
  - rm config.toml && cp themes/gruvhugo/exampleSite/config.toml . 
  - ls -a
  - cd ..
  artifacts:
    paths:
    - test

pages:
  stage: deploy
  image: registry.gitlab.com/pages/hugo:latest
  script:
  - ls && cd test
  - hugo
  - ls public
  artifacts:
    paths:
    - test/public
  only:
  - master

